baseurl = "http://localhost/"
contentdir = "content"
languageCode = "en-us"
title = "Docker UCP Beta Docs"
theme = "hugo-foundation"
canonifyurls = false
relativeURLs = true
verbose = true

[blackfriday]
  fractions = false
  smartDashes = false
  plainIdAnchors = true
  sourceRelativeLinksEval = true
